# Generated by Django 4.0.8 on 2023-04-05 03:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_alter_product_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='product',
            table='XXX',
        ),
    ]
